truncate -s 1K ./a
truncate -s 2K ./b
truncate -s 4K ./c
truncate -s 8K ./d
truncate -s 16K ./e
truncate -s 32K ./f
truncate -s 64K ./g
truncate -s 128K ./h
truncate -s 256K ./i
truncate -s 512K ./j
truncate -s 1M ./k
truncate -s 2M ./l
truncate -s 4M ./m
truncate -s 8M ./n
truncate -s 16M ./o
truncate -s 32M ./p
truncate -s 64M ./q
truncate -s 128M ./r