name: build
on: [push, pull_request]

jobs:
  lab1_v1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1/v1/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make

  lab1_v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1/v2/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make

  lab1_v3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1/v3/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make

  lab2_v1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab2/v1/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make

  lab2_v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab2/v2/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make
