name: build
on: [push, pull_request]

jobs:
  lab1/v1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1/v1/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make

  lab1/v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1/v2/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make

  lab1/v3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1/v3/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: make
